build image:
  stage: build
  image: docker
  services:
   - docker:dind
  script:
      - cd src/app
      - sudo docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
      - docker build -t $CI_REGISTRY_IMAGE .
      - docker push $CI_REGISTRY_IMAGE