# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this f>
# reopened with the relevant failures.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-minikube1
    name: hello-minikube1
    namespace: default
    resourceVersion: "1188"
  uid: 7ebaabe9-0bca-44b7-9205-40e1b52756be
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
    selector:
      matchLabels:
      app: hello-minikube1
        strategy:
          rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-minikube1
    spec:
      containers:
- image: registry.gitlab.com/dsurfer/hello-kuber
        imagePullPolicy: Always
        name: hello-kuber
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

